//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentistShopDBEntities : DbContext
    {
        public DentistShopDBEntities()
            : base("name=DentistShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Features> Features { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductFeatures> ProductFeatures { get; set; }
        public virtual DbSet<ShopUser> ShopUser { get; set; }
        public virtual DbSet<Likes> Likes { get; set; }
        public virtual DbSet<ProductComments> ProductComments { get; set; }
        public virtual DbSet<ProductGalleries> ProductGalleries { get; set; }
        public virtual DbSet<ProductGroup> ProductGroup { get; set; }
        public virtual DbSet<ProductSelectedGroups> ProductSelectedGroups { get; set; }
        public virtual DbSet<Rates> Rates { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<OrderListShopCarts> OrderListShopCarts { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
    }
}
