//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(ProductGalleriesMetaData))]
    public partial class ProductGalleries
    {
        public int galleryId { get; set; }
        public int productId { get; set; }
        public string imageName { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
