//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(ShoppingCartMetaData))]
    public partial class ShoppingCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCart()
        {
            this.OrderListShopCarts = new HashSet<OrderListShopCarts>();
        }
    
        public int cartid { get; set; }
        public int productId { get; set; }
        public int count { get; set; }
        public int userId { get; set; }
        public int wholeprice { get; set; }
        public System.DateTime sabtDate { get; set; }
        public bool isfinal { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ShopUser ShopUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderListShopCarts> OrderListShopCarts { get; set; }
    }
}
