//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    internal class OrdersMetaData
    {
        public int orderid { get; set; }
        public int userId { get; set; }
        public int wholeprice { get; set; }
        public System.DateTime sabtDate { get; set; }
        public bool isfinal { get; set; }
        public long RefID { get; set; }


    }
}