//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    internal class OrderListShopCartsMetaData
    {
        public int id { get; set; }
        public int orderid { get; set; }
        public int userId { get; set; }
        public int cartid { get; set; }
        public bool isfinal { get; set; }

    }
}