//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    internal class ProductMetaData
    {
        [Key]
        public int productId { get; set; }
        [Display(Name = "عنوان")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [MaxLength(300)]
        public string productName { get; set; }
        [Display(Name = "قیمت")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        public int Price { get; set; }
        [Display(Name = "درصد تخفیف")]
        public Nullable<int> discount { get; set; }
        [Display(Name = "قیمت کل")]
        public Nullable<int> productPriceWithDiscont { get; set; }
        [Display(Name = "تعداد")]
        public Nullable<int> productcount { get; set; }

        [Display(Name = "تصویر")]
        public string imageName { get; set; }
        [Display(Name = "تاریخ ایجاد")]
        [DisplayFormat(DataFormatString = "{0: yyyy/MM/dd}")]
        public System.DateTime createDate { get; set; }
    }
}