//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    internal class ProductGalleriesMetaData
    {
        [Key]
        public int galleryId { get; set; }
        [Display(Name = "کالا")]
        public int productId { get; set; }
        [Display(Name = "تصویر")]
        public string imageName { get; set; }

    }
}