//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    internal class ProductCommentsMetaData
    {
        [Key]
        public int commentId { get; set; }
        [Display(Name = "کالا")]
        public int productId { get; set; }
        [Display(Name = "کاربر")]
        public int userId { get; set; }
        [Display(Name = "تاریخ ثبت")]
        public System.DateTime createDate { get; set; }
        [Display(Name = "متن")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [MaxLength(800)]
        public string commentText { get; set; }
        public Nullable<int> parentId { get; set; }
    }
}