//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    internal class ShopUserMetaData
    {
        [Key]
        public int userId { get; set; }
        [Display(Name = "نام کاربری")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]

        public string userName { get; set; }
        [Display(Name = "نام")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]

        public string firstName { get; set; }
        [Display(Name = "نام خانوادگی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]

        public string lastName { get; set; }
        [Display(Name = "ایمیل")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]
        [EmailAddress(ErrorMessage = "ایمیل وارد شده معتبر نمی باشد.")]

        public string emailAddress { get; set; }
        [Display(Name = "رمز عبور")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید.")]

        public string password { get; set; }
        [Display(Name = "عکس")]
        public string pic { get; set; }
        [Display(Name = "عنوان نقش")]
        public int RoleId { get; set; }
        [Display(Name = "کد فعالسازی")]

        public string ActiveCode { get; set; }
        [Display(Name = "فعال/غیرفعال")]

        public bool IsActive { get; set; }
        [Display(Name = "تاریخ ثبت نام")]

        public System.DateTime RegisterDate { get; set; }
        [Display(Name = "موبایل")]

        public string phone { get; set; }
        [Display(Name = "آدرس")]
        public string Address { get; set; }

    }
}